### ISSUE TITLE
This site can't be reached error on some pages

### ISSUE THREAD

**Issue by wilos** [MegatronKing/NetBare#10]
We are seeing a reproducible error in some URLs, e.g. 

https://www.elotrolado.net/index.php

In logcat we see:

2019-02-15 13:35:06.912 1331-1569/com.github.megatronking.netbare.sample E/NetBare: Read error: ssl=0x966eca80: Failure in SSL library, usually a protocol error
    error:10000103:SSL routines:OPENSSL_internal:INVALID_ALPN_PROTOCOL (external/boringssl/src/ssl/t1_lib.cc:1464 0xa6f2c9e0:0x00000000)
    error:10000095:SSL routines:OPENSSL_internal:ERROR_PARSING_EXTENSION (external/boringssl/src/ssl/t1_lib.cc:2979 0x96551a00:0x00000001)
    error:100000be:SSL routines:OPENSSL_internal:PARSE_TLSEXT (external/boringssl/src/ssl/handshake_client.cc:1049 0xa6f2c9e0:0x00000000)

and in Chrome it shows:

This site can't be reached.
ERR_CONNECTION_CLOSED

and does not load the page.

Tested with latest NetBare sample on Android 8.1 and 9.0 devices

**Comment by MegatronKing** [comment]
Many thanks for your reports, it is an ALPN issue caused by my code.

**Comment by MegatronKing** [comment]
Fixed!

**Comment by joseluisametller** [comment]
I confirm this has been fixed 🎉

**Comment by wilos** [comment]
Unfortunately this problem is still occurring on Android 8.1 and 9.0 devices after the latest code changes. The error log is the same as the one reported. On Android 7.0 and 8.0 it is working fine, so it looks like an issue with 8.1+ devices. Please let me know if you have problems reproducing the issue, on our devices it is 100% reproducible on Android 8.1+

**Comment by MegatronKing** [comment]
Fixed now! Thanks wilos, I made a stupid mistake -_-

**Comment by wilos** [comment]
Great, I can confirm that this is working fine now, excellent!
